// Auto-generated by the factory implementation agent for issue #3.
// Issue: update doc

export function feature3(input) {
  if (!input || typeof input.ok !== 'boolean') {
    return { state: 'error', message: 'invalid input' };
  }
  return input.ok
    ? { state: 'success', message: 'done' }
    : { state: 'error', message: 'not ok' };
}
