// Auto-generated by the factory implementation agent for issue #5.
// Issue: Fix the broken copy-to-clipboard button

export function feature5(input: { ok: boolean }): { state: 'success' | 'error'; message: string } {
  if (!input || typeof input.ok !== 'boolean') {
    return { state: 'error', message: 'invalid input' };
  }
  return input.ok
    ? { state: 'success', message: 'done' }
    : { state: 'error', message: 'not ok' };
}
